# Generated by Django 5.1.7 on 2025-03-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='research_papers/')),
            ],
        ),
    ]
