# Generated by Django 5.1.7 on 2025-04-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0002_researchpaper_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchpaper',
            old_name='authors',
            new_name='author',
        ),
    ]
