# Generated by Django 5.1.7 on 2025-05-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0007_editorialboardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
