# Generated by Django 5.1.7 on 2025-06-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0008_hitcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsInstructionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='authors_instruction/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Authors Instruction PDF',
                'verbose_name_plural': 'Authors Instruction PDF',
            },
        ),
    ]
