# Generated by Django 5.1.7 on 2025-06-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0009_authorsinstructionpdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='researchpaper',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='journalapp.bookvolume'),
        ),
    ]
