# Generated by Django 6.1 on 2026-08-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0011_add_paper_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialboardmember',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
